theme: jekyll-theme-midnight
title: "UnaShield"
description: "Developer and hardware docs for the UnaShield Sigfox Shield for Arduino"
logo: "https://raw.githubusercontent.com/UnaBiz/unashield/master/img/etc/unashield-logo.png"
google_analytics: "UA-89065364-4"
verbose: true

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-menus
  - jekyll-assets
  - jekyll-pdf
exclude:
  - Gemfile
  - Gemfile.lock
