theme: jekyll-theme-midnight
title: "UnaShield"
description: "Developer and hardware docs for the UnaShield Sigfox Shield for Arduino"
logo: "https://storage.googleapis.com/unabiz-media/unashield/hardware/unashield-logo.png"
google_analytics: "UA-89065364-4"

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-menus
  - jekyll-assets
  - jekyll-pdf
exclude:
  - Gemfile
  - Gemfile.lock
