source 'https://rubygems.org'

# For previewing pages.
gem "github-pages", group: :jekyll_plugins

group :jekyll_plugins do
  # Theme, sitemap, SEO.
  gem "jekyll-theme-midnight"
  gem "jekyll-sitemap"
  gem "jekyll-seo-tag"

  # Navigation menu.
  gem "jekyll-menus"

  # For generating PDF.
  gem "jekyll-assets"
  gem "jekyll-pdf"
end
